### ISSUE TITLE
Next main version?

### ISSUE THREAD

**Issue by Pocokk** [akiomik/vimeo-dl#45]
Dear akiomik,

The last update was little bit over a year ago, however since then there were numerous fixes and additions to the program. Do you plan to release another major update in the (near) future? 

Thank you very much, best regards,
Pocok

**Comment by akiomik** [comment]
Hi, I'm not planning a major update at this time. Instead, I'll release v0.2.0 today

**Comment by Pocokk** [comment]
Thank you very much.

**Comment by akiomik** [comment]
v0.2.0 has been released🚀 

https://github.com/akiomik/vimeo-dl/releases/tag/v0.2.0
