### ISSUE TITLE
Vimeo-dl command not found

### ISSUE THREAD

**Issue by ferniibowie** [akiomik/vimeo-dl#7]
Hello! I cloned the files to Kali Linux and when I run some command I get "vimeo-dl command not found". Can you help me?

**Comment by akiomik** [comment]
Hi! Which version of Go are you using? If it is 1.6 or later, try `go install github.com/akiomik/vimeo-dl` instead of `go get -u github.com/akiomik/vimeo-dl`. `vimeo-dl` will install in `$GOBIN` or `$GOPATH/bin`.

**Comment by ferniibowie** [comment]
Sorry but... what operating system should I use?  I am trying to clone it from kali linux with the "git clone" command.

**Comment by akiomik** [comment]
You can use Windows, macOS, or Linux (probably includes Kali Linux) as your OS, but you must have Go installed.
Go is a programming language, and this project is written in Go. This repository does not contain the binary (i.e. `vimeo-dl`), so you need to compile it with `go install`.

If you do not have Go installed on your system, please try installing it first.
https://go.dev/doc/install

**Comment by akiomik** [comment]
I've just released vimeo-dl v0.0.2 and uploaded the binary to the release page 🎉 
This binaries don't require Go to install, so please try it out.

https://github.com/akiomik/vimeo-dl/releases/tag/v0.0.2

**Comment by ferniibowie** [comment]
Thanks for everything! The file downloaded using Go worked fine for me! You are a genius :) Great job
